on: [push]

jobs:
  docker-login-build-tag-push:
    runs-on: ubuntu-latest
    name: Docker Login, Build, Tag & Push
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build, Tag & Publish Image to DockerHub
        uses: dinushchathurya/build-tag-push-action@v1.0.4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          context: .
          file: Dockerfile
          repoOwner: ${{ secrets.DOCKER_USERNAME }}
          repository:  nodejs-docker
          tag: 1.0.0
